feat: add missing purl types
package-url/packageurl-go pull request #43
Opened 2023-04-03 05:25 UTC by mcombuechen

We are missing support for a few Package URL types in this lib, so I referenced [the list of known `purl` types](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#known-purl-types) and added the ones that were not implemented yet.

This adds `purl` types `alpm`, `apk`, `huggingface`, `mlflow`, `qpkg`, `pub` and `swid`.

2023-04-03 18:33 UTC, alowayed requested changes
Please update typeAdjustNamespace and typeAdjustName and add valid test cases for each type in test-suite-data.json.

Some example test cases are:
```
{
    "description": "valid alpm purl",
    "purl": "pkg:alpm/arch/pacman@6.0.1-1?arch=x86_64",
    "canonical_purl": "pkg:alpm/arch/pacman@6.0.1-1?arch=x86_64",
    "type": "alpm",
    "namespace": "arch",
    "name": "pacman",
    "version": "6.0.1-1",
    "qualifiers": {"arch": "x86_64"},
    "subpath": null,
    "is_invalid": false
  },
  {
    "description": "valid apk purl",
    "purl": "pkg:apk/alpine/curl@7.83.0-r0?arch=x86",
    "canonical_purl": "pkg:apk/alpine/curl@7.83.0-r0?arch=x86",
    "type": "apk",
    "namespace": "alpine",
    "name": "curl",
    "version": "7.83.0-r0",
    "qualifiers": {"arch": "x86_64"},
    "subpath": null,
    "is_invalid": false
  }
```

I'm not

2023-04-05 06:53 UTC, mcombuechen commented
Thanks for the feedback @alowayed, will add that and ping you once it's pushed.

2023-04-05 07:53 UTC, mcombuechen commented
@alowayed I decided to leave out missing types `mlflow`, `pub` and `swid`, since the sanitization logic for those types gets rather complex and would introduce too many changes. I'll try to add them in upcoming PRs. For now, keeping types `alpm`, `apk`, `huggingface` and `qpkg`.

Added test cases, please let me know what you think.

2023-04-12 17:42 UTC, alowayed approved these changes

2023-04-12 17:42 UTC, alowayed commented on packageurl.go
> +func typeAdjustVersion(purlType, version string) string {
👍

2023-06-19 14:39 UTC, pombredanne commented
@mcombuechen This looks decent to me... can you please sync up with @shibumi too?
You both have maintainer rights now.

2023-06-20 05:45 UTC, mcombuechen commented
A `huggingface` type [was added meanwhile](#46), removed that part of the code.

2023-06-20 05:46 UTC, mcombuechen commented
Thanks @pombredanne and @alowayed, can you check again?

2023-06-20 05:47 UTC, mcombuechen commented on packageurl.go
> +func typeAdjustVersion(purlType, version string) string {
Was already added in #46

2023-06-22 04:37 UTC, mcombuechen commented
Hey @shibumi would you be up for a review of this?

2023-06-22 05:39 UTC, shibumi commented
@mcombuechen sure 👍 I'll  take a look today.

2023-06-22 05:41 UTC, shibumi approved these changes

2023-06-22 05:42 UTC, shibumi commented
LGTM!

2023-06-22 05:42 UTC, merged